### PR TITLE
Changed formatting for PVS Memory check

### PR DESCRIPTION
**Pull request by mikekacz**
proposed fix for Issue #16

### CODE REVIEW

**Comment by ryanchauvin** [comment]
I'm get a U for my memory usage on all three of my PVS Servers within the HTML email with this change.

**Comment by mikekacz** [comment]
Can you tell me which version of PS you are running?

On May 22, 2017 22:22, "ryanchauvin" <notifications@github.com> wrote:

I'm get a U for my memory usage on all three of my PVS Servers within the
HTML email with this change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sacha81/citrix-pvs-healthcheck/pull/17#issuecomment-303209540>,
or mute the thread

**Comment by ryanchauvin** [comment]
PS v5

**Comment by mikekacz** [comment]
Hmm
I was testing it on v3.
Will check tomorrow.

**Pull request merged**
